run:
  timeout: 5m
  tests: false
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - godox
    - goimports
    - gosec
    - importas
    - lll
    - maintidx
    - makezero
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - reassign
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - wrapcheck
